"""血缘解析穷举回归矩阵（方言 × 语句 × 结构 × 表达式 × 边界）。

对 9 种方言 × 90+ 生产场景做全量回归：每个场景断言表级血缘（TE）与字段级
血缘（FE）的精确输出集合（为空即无血缘边）。本矩阵固化历轮方言核查验证过的
全部行为，防止未来改动引入回归，并覆盖 parser 中大量降级/边界分支。

场景期望值均经真实 sqlglot 25.34.1（对齐生产 requirements pin）验证。
"""

# MATRIX 数据表的 SQL 文本较长（保持完整可读），文件级豁免行长限制
# ruff: noqa: E501

from __future__ import annotations

import pytest

from app.services.lineage.parser import (
    extract_field_lineage,
    extract_table_lineage,
    extract_upstream_deps,
    node_column,
    node_dimension,
    node_field,
    node_metric,
    node_table,
)

#: 场景表：(id, dialect, sql, target_table, 期望 TE 集合, 期望 FE 集合)
#: TE 元素形如 ``ods.s->dws.t``；FE 元素形如 ``ods.s.id->dws.t.id``。
MATRIX: list[tuple[str, str, str, str | None, set[str], set[str]]] = [
    # ---------- 方言专属语法 ----------
    (
        "oracle_insert_all",
        "oracle",
        "INSERT ALL INTO t1 (id) VALUES (s.id) INTO t2 (id, v) VALUES (s.id, s.v) SELECT id, v FROM ods.s",
        None,
        {"ods.s->t1", "ods.s->t2"},
        {"ods.s.id->t1.id", "ods.s.id->t2.id", "ods.s.v->t2.v"},
    ),
    (
        "oracle_insert_first",
        "oracle",
        "INSERT FIRST WHEN v > 10 THEN INTO t1 (id) VALUES (s.id) ELSE INTO t2 (id) VALUES (s.id) SELECT id, v FROM ods.s",
        None,
        {"ods.s->t1", "ods.s->t2"},
        {"ods.s.id->t1.id", "ods.s.id->t2.id"},
    ),
    (
        "oracle_connect_by",
        "oracle",
        "INSERT INTO t SELECT id, parent FROM ods.org START WITH parent IS NULL CONNECT BY PRIOR id = parent",
        None,
        {"ods.org->t"},
        {"ods.org.id->t.id", "ods.org.parent->t.parent"},
    ),
    (
        "pg_select_into_table",
        "postgres",
        "SELECT id, name INTO newtbl FROM ods.orders",
        None,
        {"ods.orders->newtbl"},
        {"ods.orders.id->newtbl.id", "ods.orders.name->newtbl.name"},
    ),
    (
        "tsql_select_into",
        "tsql",
        "SELECT id, name INTO dws.newtbl FROM ods.orders",
        None,
        {"ods.orders->dws.newtbl"},
        {"ods.orders.id->dws.newtbl.id", "ods.orders.name->dws.newtbl.name"},
    ),
    (
        "tsql_insert_top",
        "tsql",
        "INSERT TOP (10) INTO dws.t SELECT id, name FROM ods.orders",
        None,
        {"ods.orders->dws.t"},
        {"ods.orders.id->dws.t.id", "ods.orders.name->dws.t.name"},
    ),
    (
        "tsql_nolock",
        "tsql",
        "INSERT INTO dws.t SELECT o.id FROM ods.orders o WITH (NOLOCK)",
        None,
        {"ods.orders->dws.t"},
        {"ods.orders.id->dws.t.id"},
    ),
    (
        "ck_array_join",
        "clickhouse",
        "INSERT INTO t SELECT item, id FROM ods.a ARRAY JOIN a.items AS item",
        None,
        {"ods.a->t"},
        {"ods.a.item->t.item", "ods.a.id->t.id"},
    ),
    (
        "ck_final",
        "clickhouse",
        "INSERT INTO t SELECT id, v FROM ods.t FINAL",
        None,
        {"ods.t->t"},
        {"ods.t.id->t.id", "ods.t.v->t.v"},
    ),
    (
        "ck_ctas_engine",
        "clickhouse",
        "CREATE TABLE t ENGINE = MergeTree ORDER BY id AS SELECT id, v FROM ods.s",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.v->t.v"},
    ),
    (
        "ck_with_totals",
        "clickhouse",
        "INSERT INTO t SELECT g, SUM(v) AS sv FROM ods.s GROUP BY g WITH TOTALS",
        None,
        {"ods.s->t"},
        {"ods.s.g->t.g", "ods.s.v->t.sv"},
    ),
    (
        "doris_ctas_distributed",
        "doris",
        "CREATE TABLE dws.t DISTRIBUTED BY HASH(id) BUCKETS 10 PROPERTIES('replication_num'='1') AS SELECT id, v FROM ods.s",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id", "ods.s.v->dws.t.v"},
    ),
    (
        "doris_aggregate_key",
        "doris",
        "CREATE TABLE t (id INT, v INT SUM) AGGREGATE KEY(id) DISTRIBUTED BY HASH(id) AS SELECT id, v FROM ods.s",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.v->t.v"},
    ),
    (
        "doris_with_label",
        "doris",
        "INSERT INTO dws.t WITH LABEL 'load_001' SELECT id FROM ods.s",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id"},
    ),
    (
        "starrocks_primary_key",
        "starrocks",
        "CREATE TABLE t (id INT, v INT) PRIMARY KEY(id) AS SELECT id, v FROM ods.s",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.v->t.v"},
    ),
    (
        "hive_insert_overwrite_partition",
        "hive",
        "INSERT OVERWRITE TABLE dws.t PARTITION(dt='2026-01-01') SELECT id, v FROM ods.s",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id", "ods.s.v->dws.t.v"},
    ),
    (
        "hive_lateral_view_outer",
        "hive",
        "INSERT INTO t SELECT e.tag, a.id FROM ods.a LATERAL VIEW OUTER EXPLODE(a.tags) e AS tag",
        None,
        {"ods.a->t"},
        {"ods.a.tags->t.tag", "ods.a.id->t.id"},
    ),
    (
        "hive_dynamic_partition",
        "hive",
        "INSERT OVERWRITE TABLE dws.t PARTITION(dt) SELECT id, v, dt FROM ods.s",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id", "ods.s.v->dws.t.v", "ods.s.dt->dws.t.dt"},
    ),
    (
        "spark_ctas_stored",
        "spark",
        "CREATE TABLE dws.t STORED AS PARQUET AS SELECT id, v FROM ods.s",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id", "ods.s.v->dws.t.v"},
    ),
    (
        "spark_using_join",
        "spark",
        "INSERT INTO t SELECT a.id, b.v FROM ods.a a JOIN ods.b b USING (id)",
        None,
        {"ods.a->t", "ods.b->t"},
        {"ods.a.id->t.id", "ods.b.v->t.v"},
    ),
    (
        "mysql_insert_ignore",
        "mysql",
        "INSERT IGNORE INTO t SELECT id, v FROM ods.s",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.v->t.v"},
    ),
    (
        "mysql_backtick_table",
        "mysql",
        "INSERT INTO `dws`.`t` SELECT `id`, `v` FROM `ods`.`s`",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id", "ods.s.v->dws.t.v"},
    ),
    (
        "pg_quoted_schema",
        "postgres",
        'INSERT INTO dws.t SELECT s."id", s."v" FROM "ods"."s1" s',
        None,
        {"ods.s1->dws.t"},
        {"ods.s1.id->dws.t.id", "ods.s1.v->dws.t.v"},
    ),
    (
        "mysql_replace_into",
        "mysql",
        "REPLACE INTO dws.t SELECT id, v FROM ods.s",
        None,
        {"ods.s->dws.t"},
        {"ods.s.id->dws.t.id", "ods.s.v->dws.t.v"},
    ),
    (
        "create_view",
        "mysql",
        "CREATE VIEW dws.v_sales AS SELECT id, v FROM ods.orders",
        None,
        {"ods.orders->dws.v_sales"},
        {"ods.orders.id->dws.v_sales.id", "ods.orders.v->dws.v_sales.v"},
    ),
    (
        "create_view_or_replace",
        "mysql",
        "CREATE OR REPLACE VIEW dws.v AS SELECT id FROM ods.orders",
        None,
        {"ods.orders->dws.v"},
        {"ods.orders.id->dws.v.id"},
    ),
    (
        "create_temp_view",
        "spark",
        "CREATE TEMPORARY VIEW dws.v AS SELECT id FROM ods.s",
        None,
        {"ods.s->dws.v"},
        {"ods.s.id->dws.v.id"},
    ),
    (
        "create_table_like_no_edge",
        "mysql",
        "CREATE TABLE dws.t LIKE ods.s",
        None,
        set(),
        set(),
    ),
    # ---------- 集合运算 / CTE / 子查询 ----------
    (
        "setop_except_field",
        "mysql",
        "INSERT INTO t SELECT id FROM ods.a EXCEPT SELECT id FROM ods.b",
        None,
        {"ods.a->t", "ods.b->t"},
        {"ods.a.id->t.id", "ods.b.id->t.id"},
    ),
    (
        "setop_intersect_field",
        "mysql",
        "INSERT INTO t SELECT id FROM ods.a INTERSECT SELECT id FROM ods.b",
        None,
        {"ods.a->t", "ods.b->t"},
        {"ods.a.id->t.id", "ods.b.id->t.id"},
    ),
    (
        "cte_chain_field",
        "mysql",
        "WITH cte AS (SELECT id, name FROM ods.src) INSERT INTO dws.dest SELECT cte.id AS x, cte.name AS y FROM cte",
        None,
        {"ods.src->dws.dest"},
        {"ods.src.id->dws.dest.x", "ods.src.name->dws.dest.y"},
    ),
    (
        "cte_same_name_shadow",
        "postgres",
        "WITH cte1 AS (SELECT id FROM ods.a) INSERT INTO dws.t SELECT c1.id FROM ods.cte1 c1 JOIN cte1 ON c1.id = cte1.id",
        None,
        {"ods.cte1->dws.t", "ods.a->dws.t"},
        {"ods.cte1.id->dws.t.id"},
    ),
    (
        "cte_union_outer",
        "mysql",
        "WITH x AS (SELECT id FROM ods.a UNION ALL SELECT id FROM ods.b) INSERT INTO dws.t SELECT id FROM x",
        None,
        {"ods.a->dws.t", "ods.b->dws.t"},
        {"ods.a.id->dws.t.id", "ods.b.id->dws.t.id"},
    ),
    (
        "nested_union_derived",
        "mysql",
        "INSERT INTO t SELECT x FROM (SELECT a.id AS x FROM ods.a UNION ALL SELECT b.uid AS x FROM ods.b) u",
        None,
        {"ods.a->t", "ods.b->t"},
        {"ods.a.id->t.x", "ods.b.uid->t.x"},
    ),
    (
        "subquery_alias_no_leak",
        "mysql",
        "SELECT t1.id, t3.name FROM ods.t1 t1 JOIN (SELECT id FROM ods.t2) t2 ON t1.id=t2.id JOIN ods.t3 t3 ON t1.id=t3.id",
        None,
        set(),
        set(),
    ),
    (
        "recursive_cte_table_ok",
        "postgres",
        "WITH RECURSIVE r AS (SELECT id, parent FROM ods.org WHERE parent IS NULL UNION ALL SELECT o.id, o.parent FROM ods.org o JOIN r ON o.parent=r.id) INSERT INTO t SELECT id FROM r",
        None,
        {"ods.org->t"},
        {"ods.org.id->t.id"},
    ),
    (
        "self_join",
        "mysql",
        "INSERT INTO t SELECT a.id, b.id FROM ods.e a JOIN ods.e b ON a.id=b.parent_id",
        None,
        {"ods.e->t"},
        {"ods.e.id->t.id"},
    ),
    (
        "same_table_self_ref_no_edge",
        "mysql",
        "INSERT INTO dws.t SELECT id, v FROM dws.t",
        None,
        set(),
        set(),
    ),
    (
        "expr_multi_source",
        "mysql",
        "INSERT INTO t SELECT a.col + b.col AS sum_col FROM ods.a a JOIN ods.b b ON a.id=b.id",
        None,
        {"ods.a->t", "ods.b->t"},
        {"ods.a.col->t.sum_col", "ods.b.col->t.sum_col"},
    ),
    (
        "case_branch",
        "mysql",
        "INSERT INTO t SELECT CASE WHEN a.v > 0 THEN 'p' ELSE 'n' END AS flag FROM ods.a",
        None,
        {"ods.a->t"},
        {"ods.a.v->t.flag"},
    ),
    (
        "scalar_subquery",
        "mysql",
        "INSERT INTO t SELECT (SELECT MAX(v) FROM ods.d) AS calc FROM ods.s",
        None,
        {"ods.s->t", "ods.d->t"},
        {"ods.d.v->t.calc"},
    ),
    (
        "lateral_subquery_pg",
        "postgres",
        "INSERT INTO t SELECT x.v FROM ods.s, LATERAL (SELECT v FROM ods.d WHERE d.id=s.id) x",
        None,
        {"ods.s->t", "ods.d->t"},
        {"ods.d.v->t.v"},
    ),
    (
        "named_window",
        "mysql",
        "INSERT INTO t SELECT ROW_NUMBER() OVER w AS rn, g, ts FROM ods.s WINDOW w AS (PARTITION BY g ORDER BY ts)",
        None,
        {"ods.s->t"},
        {
            "ods.s.g->t.rn",
            "ods.s.ts->t.rn",
            "ods.s.g->t.g",
            "ods.s.ts->t.ts",
        },
    ),
    (
        "window_frame",
        "mysql",
        "INSERT INTO t SELECT SUM(v) OVER (PARTITION BY g ORDER BY ts ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS sv FROM ods.s",
        None,
        {"ods.s->t"},
        {"ods.s.g->t.sv", "ods.s.v->t.sv", "ods.s.ts->t.sv"},
    ),
    (
        "unpivot_values_multi_source",
        "mysql",
        "INSERT INTO t SELECT u.v FROM ods.s UNPIVOT (v FOR k IN (a, b, c)) AS u",
        None,
        {"ods.s->t"},
        {"ods.s.a->t.v", "ods.s.b->t.v", "ods.s.c->t.v"},
    ),
    (
        "pg_unnest_alias",
        "postgres",
        "INSERT INTO t SELECT u.v, a.id FROM ods.a, LATERAL UNNEST(a.items) AS u(v)",
        None,
        {"ods.a->t"},
        {"ods.a.items->t.v", "ods.a.id->t.id"},
    ),
    (
        "hive_lateral_view_explode",
        "hive",
        "INSERT INTO t SELECT e.tag, a.id FROM ods.a LATERAL VIEW EXPLODE(a.tags) e AS tag",
        None,
        {"ods.a->t"},
        {"ods.a.tags->t.tag", "ods.a.id->t.id"},
    ),
    (
        "pg_update_from",
        "postgres",
        "UPDATE dws.t SET v = s.v FROM ods.s WHERE t.id = s.id",
        None,
        {"ods.s->dws.t"},
        {"ods.s.v->dws.t.v"},
    ),
    (
        "pg_multi_col_update",
        "postgres",
        "UPDATE dws.t SET (a, b) = (s.a, s.b) FROM ods.s WHERE t.id = s.id",
        None,
        {"ods.s->dws.t"},
        {"ods.s.a->dws.t.a", "ods.s.b->dws.t.b"},
    ),
    (
        "mysql_multi_table_update_cross_set",
        "mysql",
        "UPDATE t1 JOIN t2 ON t1.id=t2.id SET t1.v=t2.v, t2.w=t1.x",
        None,
        {"t2->t1"},
        {"t2.v->t1.v", "t1.x->t2.w"},
    ),
    (
        "update_cte_source",
        "postgres",
        "WITH s AS (SELECT id, v FROM ods.src) UPDATE dws.t SET v = s.v FROM s WHERE t.id = s.id",
        None,
        {"ods.src->dws.t"},
        {"ods.src.v->dws.t.v"},
    ),
    (
        "update_subquery_value",
        "mysql",
        "UPDATE dws.t SET v = (SELECT MAX(x) FROM ods.src) WHERE id = 1",
        None,
        {"ods.src->dws.t"},
        {"ods.src.x->dws.t.v"},
    ),
    (
        "merge_update_insert",
        "mysql",
        "MERGE INTO tgt USING src ON tgt.id=src.id WHEN MATCHED THEN UPDATE SET tgt.v=src.v WHEN NOT MATCHED THEN INSERT (id, v) VALUES (src.id, src.v)",
        None,
        {"src->tgt"},
        {"src.v->tgt.v", "src.id->tgt.id"},
    ),
    (
        "merge_insert_no_column_list",
        "hive",
        "MERGE INTO tgt USING src ON tgt.id=src.id WHEN NOT MATCHED THEN INSERT VALUES (src.id, src.name)",
        None,
        {"src->tgt"},
        {"src.id->tgt.id", "src.name->tgt.name"},
    ),
    (
        "insert_column_list_mapping",
        "mysql",
        "INSERT INTO tgt (a, b) SELECT x, y FROM ods.s",
        None,
        {"ods.s->tgt"},
        {"ods.s.x->tgt.a", "ods.s.y->tgt.b"},
    ),
    (
        "ctas_column_list_mapping",
        "mysql",
        "CREATE TABLE tgt (a, b) AS SELECT x, y FROM ods.s",
        None,
        {"ods.s->tgt"},
        {"ods.s.x->tgt.a", "ods.s.y->tgt.b"},
    ),
    (
        "select_star_degraded",
        "mysql",
        "INSERT INTO t SELECT * FROM ods.a",
        None,
        {"ods.a->t"},
        set(),
    ),
    (
        "select_alias_star_degraded",
        "mysql",
        "INSERT INTO t SELECT a.* AS x FROM ods.a",
        None,
        {"ods.a->t"},
        set(),
    ),
    (
        "qualified_star_degraded",
        "mysql",
        "INSERT INTO t SELECT a.* FROM ods.a",
        None,
        {"ods.a->t"},
        set(),
    ),
    (
        "pure_select_no_target_no_edge",
        "mysql",
        "SELECT o.id, u.name FROM ods.orders o JOIN ods.users u ON o.uid = u.id",
        None,
        set(),
        set(),
    ),
    (
        "pure_select_with_target",
        "mysql",
        "SELECT id, name FROM ods.orders",
        "dws.result",
        {"ods.orders->dws.result"},
        {"ods.orders.id->dws.result.id", "ods.orders.name->dws.result.name"},
    ),
    (
        "multi_statement",
        "mysql",
        "INSERT INTO t1 SELECT id FROM ods.a; DELETE FROM dws.old_tmp",
        None,
        {"ods.a->t1"},
        {"ods.a.id->t1.id"},
    ),
    (
        "distinct_on",
        "postgres",
        "INSERT INTO t SELECT DISTINCT ON (id) id, v FROM ods.s ORDER BY id, v DESC",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.v->t.v"},
    ),
    (
        "grouping_sets",
        "postgres",
        "INSERT INTO t SELECT g, SUM(v) FROM ods.s GROUP BY GROUPING SETS ((g), ())",
        None,
        {"ods.s->t"},
        {"ods.s.g->t.g"},
    ),
    (
        "hive_sort_by",
        "hive",
        "INSERT INTO t SELECT id, v FROM ods.s SORT BY id",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.v->t.v"},
    ),
    (
        "qualify_window",
        "spark",
        "INSERT INTO t SELECT id, ROW_NUMBER() OVER (PARTITION BY g ORDER BY ts) AS rn FROM ods.s QUALIFY rn = 1",
        None,
        {"ods.s->t"},
        {"ods.s.id->t.id", "ods.s.g->t.rn", "ods.s.ts->t.rn"},
    ),
    # ---------- 边界/降级（不崩 + 合理 0 边） ----------
    ("empty_sql", "mysql", "", None, set(), set()),
    ("comment_only", "mysql", "-- just a comment", None, set(), set()),
    ("syntax_error", "mysql", "SELECT FROM WHERE", None, set(), set()),
    ("constant_no_from", "mysql", "SELECT 1", None, set(), set()),
    ("values_no_source", "mysql", "INSERT INTO t (id, v) VALUES (1, 2)", None, set(), set()),
    (
        "on_duplicate_const",
        "mysql",
        "INSERT INTO t (id, v) VALUES (1, 2) ON DUPLICATE KEY UPDATE v = 3",
        None,
        set(),
        set(),
    ),
    ("update_const_only", "mysql", "UPDATE t SET v = 1 WHERE id = 2", None, set(), set()),
    ("update_bad_target", "mysql", "UPDATE t SET 1 = 2", None, set(), set()),
    ("merge_no_when", "mysql", "MERGE INTO tgt USING src ON tgt.id=src.id", None, set(), set()),
    (
        "merge_delete_branch",
        "mysql",
        "MERGE INTO tgt USING src ON tgt.id=src.id WHEN MATCHED AND src.flag=0 THEN DELETE",
        None,
        {"src->tgt"},
        set(),
    ),
    ("delete_join", "mysql", "DELETE t1 FROM t1 JOIN t2 ON t1.id=t2.id", None, set(), set()),
    (
        "insert_all_src_eq_target",
        "oracle",
        "INSERT ALL INTO ods.a (id) VALUES (s.id) SELECT id FROM ods.a s",
        None,
        set(),
        set(),
    ),
    (
        "window_no_alias",
        "mysql",
        "INSERT INTO t SELECT ROW_NUMBER() OVER (PARTITION BY g) FROM ods.s",
        None,
        {"ods.s->t"},
        set(),
    ),
    (
        "window_missing_def",
        "mysql",
        "INSERT INTO t SELECT ROW_NUMBER() OVER w2 FROM ods.s WINDOW w1 AS (PARTITION BY g)",
        None,
        {"ods.s->t"},
        set(),
    ),
    (
        "cte_missing_projection",
        "postgres",
        "WITH s AS (SELECT id FROM ods.src) INSERT INTO t SELECT s.missing FROM s",
        None,
        {"ods.src->t"},
        set(),
    ),
    (
        "subquery_missing_projection",
        "mysql",
        "INSERT INTO t SELECT u.missing FROM (SELECT id FROM ods.a) u",
        None,
        {"ods.a->t"},
        set(),
    ),
    (
        "unnest_no_column_list",
        "postgres",
        "INSERT INTO t SELECT u.items FROM ods.a, LATERAL UNNEST(a.items) AS u(items)",
        None,
        {"ods.a->t"},
        {"ods.a.items->t.items"},
    ),
    (
        "unnest_no_alias",
        "postgres",
        "INSERT INTO t SELECT x FROM ods.a, LATERAL UNNEST(a.items) x",
        None,
        {"ods.a->t"},
        {"ods.a.items->t.x"},
    ),
    (
        "lateral_view_no_column_list",
        "hive",
        "INSERT INTO t SELECT e FROM ods.a LATERAL VIEW EXPLODE(a.tags) e",
        None,
        {"ods.a->t"},
        {"ods.a.tags->t.e"},
    ),
    (
        "update_set_subquery_star",
        "postgres",
        "UPDATE dws.t SET v = (SELECT * FROM ods.s) WHERE id=1",
        None,
        {"ods.s->dws.t"},
        set(),
    ),
    (
        "update_set_no_cross_table",
        "postgres",
        "UPDATE dws.t SET v = v + 1 FROM ods.s WHERE t.id=s.id",
        None,
        {"ods.s->dws.t"},
        set(),
    ),
    (
        "deep_cte_chain_field_degraded",
        "mysql",
        "WITH c1 AS (SELECT id FROM ods.a), c2 AS (SELECT id FROM c1), c3 AS (SELECT id FROM c2), c4 AS (SELECT id FROM c3), c5 AS (SELECT id FROM c4), c6 AS (SELECT id FROM c5), c7 AS (SELECT id FROM c6), c8 AS (SELECT id FROM c7), c9 AS (SELECT id FROM c8), c10 AS (SELECT id FROM c9) INSERT INTO t SELECT id FROM c10",
        None,
        {"ods.a->t"},
        set(),
    ),
    # ---------- 去重 / 星号 / 窗口 / LATERAL 边界 ----------
    (
        "duplicate_edge_dedup",
        "mysql",
        "INSERT INTO t SELECT id FROM s; INSERT INTO t SELECT id FROM s",
        None,
        {"s->t"},
        {"s.id->t.id"},
    ),
    (
        "pure_select_target_self_join_dedup",
        "mysql",
        "SELECT a.id, b.id FROM ods.s a JOIN ods.s b ON a.id=b.id",
        "dws.result",
        {"ods.s->dws.result"},
        {"ods.s.id->dws.result.id"},
    ),
    (
        "insert_all_dup_target",
        "oracle",
        "INSERT ALL INTO t1 (id) VALUES (s.id) INTO t1 (v) VALUES (s.v) SELECT id, v FROM ods.s",
        None,
        {"ods.s->t1"},
        {"ods.s.v->t1.v", "ods.s.id->t1.id"},
    ),
    (
        "select_star_multi_source_degraded",
        "mysql",
        "INSERT INTO t SELECT * FROM ods.a JOIN ods.b ON a.id=b.id",
        None,
        {"ods.a->t", "ods.b->t"},
        set(),
    ),
    (
        "select_star_alias_degraded",
        "mysql",
        "INSERT INTO t SELECT * AS x FROM ods.a",
        None,
        {"ods.a->t"},
        set(),
    ),
    (
        "window_missing_def_no_derived",
        "mysql",
        "INSERT INTO t SELECT ROW_NUMBER() OVER w AS rn FROM ods.s WINDOW w1 AS (PARTITION BY g)",
        None,
        {"ods.s->t"},
        set(),
    ),
    (
        "lateral_no_match_column",
        "postgres",
        "INSERT INTO t SELECT x.other FROM ods.s, LATERAL (SELECT v FROM ods.d WHERE d.id=s.id) x",
        None,
        {"ods.s->t", "ods.d->t"},
        set(),
    ),
    (
        "unnest_no_column_list_alias",
        "postgres",
        "INSERT INTO t SELECT u FROM ods.a, LATERAL UNNEST(a.items) AS u",
        None,
        {"ods.a->t"},
        {"ods.a.items->t.u"},
    ),
    (
        "merge_using_table",
        "postgres",
        "MERGE INTO tgt USING src ON tgt.id=src.id WHEN MATCHED THEN UPDATE SET tgt.v=src.v",
        None,
        {"src->tgt"},
        {"src.v->tgt.v"},
    ),
    (
        "merge_insert_const_values_no_edge",
        "mysql",
        "MERGE INTO tgt USING src ON tgt.id=src.id WHEN NOT MATCHED THEN INSERT VALUES (1, 'x')",
        None,
        set(),
        set(),
    ),
    (
        "update_value_from_target_no_edge",
        "mysql",
        "UPDATE ods.t SET v = ods.t.x WHERE id=1",
        None,
        set(),
        set(),
    ),
]


def test_node_constructors() -> None:
    """节点标识构造函数（表/指标/维度/字段/字段别名）。"""
    assert node_table("db.tbl") == "table:db.tbl"
    assert node_metric("GMV") == "metric:GMV"
    assert node_dimension("d_region") == "dimension:d_region"
    assert node_column("db.tbl", "col") == "column:db.tbl.col"
    assert node_field("db.tbl", "col") == "field:db.tbl.col"


def test_upstream_deps_star_projection_skipped() -> None:
    """纯 SELECT ``SELECT *``：星号投影无法枚举字段，字段依赖跳过但表依赖保留。"""
    ud = extract_upstream_deps("SELECT * FROM ods.a")
    assert ud.tables == ("ods.a",)
    assert ud.fields == ()
    ud2 = extract_upstream_deps("SELECT a.* FROM ods.a a")
    assert ud2.tables == ("ods.a",)
    assert ud2.fields == ()


def _te_set(sql: str, dialect: str | None, target: str | None) -> set[str]:
    return {f"{e.source}->{e.target}" for e in extract_table_lineage(sql, dialect, target)}


def _fe_set(sql: str, dialect: str | None, target: str | None) -> set[str]:
    return {
        f"{e.source_table}.{e.source_column}->{e.target_table}.{e.target_column}"
        for e in extract_field_lineage(sql, dialect, target)
        if not e.degraded  # 降级标记边不计入精确断言（星号无法枚举列）
    }


@pytest.mark.parametrize(
    "case_id,dialect,sql,target,exp_te,exp_fe",
    MATRIX,
    ids=[c[0] for c in MATRIX],
)
def test_matrix_table_and_field_lineage(
    case_id: str,
    dialect: str,
    sql: str,
    target: str | None,
    exp_te: set[str],
    exp_fe: set[str],
) -> None:
    """穷举矩阵：表级与字段级血缘输出与真实环境验证的期望完全一致。"""
    assert _te_set(sql, dialect, target) == exp_te, f"[{case_id}] 表级血缘不符"
    assert _fe_set(sql, dialect, target) == exp_fe, f"[{case_id}] 字段级血缘不符"
