"""业务错误码枚举。

对齐 TD §5.4 统一语义表。
所有服务返回体中的 error_code 取自此枚举，禁止硬编码。
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """业务错误码枚举（对齐 TD §5.4）。"""

    # ---- 鉴权与权限 ----
    AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_APIKEY_MISSING = "AUTH_APIKEY_MISSING"
    AUTH_APIKEY_INVALID = "AUTH_APIKEY_INVALID"
    FORBIDDEN = "FORBIDDEN"
    FEATURE_DISABLED = "FEATURE_DISABLED"
    FORBIDDEN_DOMAIN = "FORBIDDEN_DOMAIN"
    FORBIDDEN_METRIC = "FORBIDDEN_METRIC"
    FORBIDDEN_DIMENSION = "FORBIDDEN_DIMENSION"
    FORBIDDEN_PII = "FORBIDDEN_PII"
    FORBIDDEN_DEPRECATED = "FORBIDDEN_DEPRECATED"
    INJECTION_DETECTED = "INJECTION_DETECTED"

    # ---- 请求校验 ----
    METRIC_NOT_FOUND = "METRIC_NOT_FOUND"
    # 指标因口径仲裁被作废（软删但带 successor），详情直访时给出友好引导而非裸 404
    METRIC_ARCHIVED = "METRIC_ARCHIVED"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"
    COMPLIANCE_BLOCKED = "COMPLIANCE_BLOCKED"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    RECONCILIATION_ALERT = "RECONCILIATION_ALERT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    EXPRESSION_INVALID = "EXPRESSION_INVALID"
    GRANULARITY_VIOLATION = "GRANULARITY_VIOLATION"
    ADDITIVITY_VIOLATION = "ADDITIVITY_VIOLATION"

    # ---- 限流与配额 ----
    RATE_LIMITED = "RATE_LIMITED"
    LLM_QUOTA_EXCEEDED = "LLM_QUOTA_EXCEEDED"

    # ---- 降级 ----
    DEPENDENCY_DEGRADED_ENGINE = "DEPENDENCY_DEGRADED_ENGINE"
    DEPENDENCY_DEGRADED_GRAPH = "DEPENDENCY_DEGRADED_GRAPH"
    DEPENDENCY_DEGRADED_LLM = "DEPENDENCY_DEGRADED_LLM"

    # ---- 质量与新鲜度 ----
    QUALITY_DOWNGRADED = "QUALITY_DOWNGRADED"
    STALE_DATA = "STALE_DATA"
    FRESHNESS_DELAYED = "FRESHNESS_DELAYED"

    # ---- 版本与迁移 ----
    METRIC_DEPRECATED = "METRIC_DEPRECATED"
    METRIC_SOURCE_DROPPED = "METRIC_SOURCE_DROPPED"
    METRIC_VERSION_SUNSET = "METRIC_VERSION_SUNSET"
    API_VERSION_SUNSET = "API_VERSION_SUNSET"

    # ---- LLM 与 AI ----
    NL_INTENT_UNRECOGNIZED = "NL_INTENT_UNRECOGNIZED"
    NL_AMBIGUOUS = "NL_AMBIGUOUS"
    NL_MAPPING_FAILED = "NL_MAPPING_FAILED"

    # ---- 系统级 ----
    INTERNAL_ERROR = "INTERNAL_ERROR"
    QUERY_TIMEOUT = "QUERY_TIMEOUT"
